package ui.old.Observers;

import domain.CImage.CImage;

import javax.swing.*;

public class JPanelCImage extends JPanel implements Observer
{
    private CImage cimage;
    
    /** Creates new form CImageObserver */
    public JPanelCImage() 
    {
        initComponents();
        jLabel.setVerticalAlignment(jLabel.TOP);
        jLabel.setHorizontalAlignment(jLabel.LEFT);
    }
    
    public JPanelCImage(CImage ci)
    {
        initComponents();
        setCImage(ci);
        jLabel.setVerticalAlignment(jLabel.TOP);
        jLabel.setHorizontalAlignment(jLabel.LEFT);

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        jLabel = new JLabel();

        jScrollPane1.setViewportView(jLabel);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setCImage(CImage ci)
    {
        if (cimage != null) cimage.setObserver(null);
        cimage = ci;
        ci.setObserver(this);
        jLabel.setIcon(new ImageIcon(cimage.getImage()));
    }
    
    public void update()
    {
        jLabel.setIcon(new ImageIcon(cimage.getImage()));
    }
    
    public CImage getCImage()
    {
        return cimage;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
