package ui.implementation.dialogs;

import domain.CImage.CImageNG;
import domain.CImage.Exceptions.CImageNGException;
import domain.CImage.Observers.JLabelBeanCImage;
import java.io.*;
import javax.swing.*;

public class DoubleMatrix extends JDialog
{
    private double Max;
    private double Min;
    private double blanc;
    private double noir;
    
    private final int D = 512;
    
    private double   matrice[][];
    private int      M,N;
    private CImageNG image;
    private int      matrice_int[][];
    
    private JLabelBeanCImage observer;
    
    /** Creates new form JDialogAfficheFourier */
    public DoubleMatrix(java.awt.Frame parent, boolean modal, double m[][], String titre)
    {
        super(parent, modal);
        initComponents();
        setTitle(titre);
        
        matrice = m;
        M = matrice.length;
        N = matrice[0].length;
        matrice_int = new int[M][N];
        try 
        {
            image = new CImageNG(M,N,0);
        } 
        catch (CImageNGException ex) 
        { System.out.println("Erreur CImageNG : " + ex.getMessage()); }
        
        observer = new JLabelBeanCImage(image);
        jScrollPane1.setViewportView(observer);
        
        jSliderNoir.setMaximum(D);
        jSliderNoir.setValue(0);
        jSliderBlanc.setMaximum(D);
        jSliderBlanc.setValue(D);
        
        // ***** Recherche du Min *****
        Min = matrice[0][0];
        for(int i=0 ; i<M ; i++)
            for(int j=0 ; j<N ; j++)
                if (matrice[i][j] < Min) Min = matrice[i][j];
        jLabelValeurMin.setText("" + Min);
        noir = Min;
        jTextFieldNoir.setText("" + noir);
        
        // ***** Recherche du Max *****
        Max = matrice[0][0];
        for(int i=0 ; i<M ; i++)
            for(int j=0 ; j<N ; j++)
                if (matrice[i][j] > Max) Max = matrice[i][j];
        jLabelValeurMax.setText("" + Max);
        blanc = Max;
        jTextFieldBlanc.setText("" + blanc);
        
        MiseAJourCImage();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new JLabel();
        jLabelValeurMax = new JLabel();
        jLabel2 = new JLabel();
        jLabelValeurMin = new JLabel();
        jScrollPane1 = new JScrollPane();
        jSliderBlanc = new JSlider();
        jSliderNoir = new JSlider();
        jTextFieldBlanc = new JTextField();
        jTextFieldNoir = new JTextField();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Valeur MAX :");

        jLabelValeurMax.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelValeurMax.setForeground(new java.awt.Color(0, 0, 255));
        jLabelValeurMax.setText("0.0");

        jLabel2.setText("Valeur MIN :");

        jLabelValeurMin.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelValeurMin.setForeground(new java.awt.Color(0, 0, 255));
        jLabelValeurMin.setText("0.0");

        jSliderBlanc.setForeground(new java.awt.Color(255, 255, 255));
        jSliderBlanc.setMaximum(1000);
        jSliderBlanc.setOrientation(JSlider.VERTICAL);
        jSliderBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderBlancMouseReleased(evt);
            }
        });
        jSliderBlanc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBlancStateChanged(evt);
            }
        });

        jSliderNoir.setForeground(new java.awt.Color(0, 1, 0));
        jSliderNoir.setMaximum(1000);
        jSliderNoir.setOrientation(JSlider.VERTICAL);
        jSliderNoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderNoirMouseReleased(evt);
            }
        });
        jSliderNoir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNoirStateChanged(evt);
            }
        });

        jTextFieldBlanc.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextFieldBlanc.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldBlanc.setHorizontalAlignment(JTextField.CENTER);
        jTextFieldBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBlancActionPerformed(evt);
            }
        });

        jTextFieldNoir.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldNoir.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextFieldNoir.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldNoir.setHorizontalAlignment(JTextField.CENTER);
        jTextFieldNoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new ImageIcon(getClass().getResource("/dd_27_p3.jpg")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValeurMin)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValeurMax)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSliderNoir, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jSliderBlanc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldBlanc, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jTextFieldNoir, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabelValeurMin)
                        .addComponent(jLabel1)
                        .addComponent(jLabelValeurMax))
                    .addComponent(jButton1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBlanc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderNoir, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jSliderBlanc, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNoir, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    image.enregistreFormatPNG(fichier);
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MiseAJourCImage()
    {
        int val;

        for(int i=0 ; i<M ; i++)
            for(int j=0 ; j<N ; j++)
            {
                if (matrice[i][j] >= blanc)
                {
                    matrice_int[i][j] = 255;
                }
                else
                {
                    if (matrice[i][j] <= noir)
                    {
                        matrice_int[i][j] = 0;
                    }
                    else
                    {
                        val = (int)((matrice[i][j] - noir)/(blanc-noir)*255+0.5);
                        if (val > 255) val = 255;
                        if (val < 0) val = 0;
                        matrice_int[i][j] = val;
                    }
                }
            }
        try 
        {
            image.setMatrice(matrice_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }
    
    private void jTextFieldNoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoirActionPerformed
        double val = Double.parseDouble(jTextFieldNoir.getText());
        if (val < Min)
        {
            jSliderNoir.setValue(0);
            return;
        }
        if (val >= blanc)
        {
            jSliderNoir.setValue(jSliderBlanc.getValue()-1);
            return;
        }
        int s = (int)((double)D*(val-Min)/(Max-Min)+0.5);
        jSliderNoir.setValue(s);

    }//GEN-LAST:event_jTextFieldNoirActionPerformed

    private void jTextFieldBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBlancActionPerformed
        double val = Double.parseDouble(jTextFieldBlanc.getText());
        if (val > Max)
        {
            jSliderBlanc.setValue(D);
            return;
        }
        if (val <= noir)
        {
            jSliderBlanc.setValue(jSliderNoir.getValue()+1);
            return;
        }
        int s = (int)((double)D*(val-Min)/(Max-Min)+0.5);
        jSliderBlanc.setValue(s);
    }//GEN-LAST:event_jTextFieldBlancActionPerformed

    private void jSliderNoirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderNoirMouseReleased
        if (jSliderNoir.getValue() >= jSliderBlanc.getValue())
            jSliderNoir.setValue(jSliderBlanc.getValue()-1);
    }//GEN-LAST:event_jSliderNoirMouseReleased

    private void jSliderBlancMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderBlancMouseReleased
        if (jSliderBlanc.getValue() <= jSliderNoir.getValue()) 
            jSliderBlanc.setValue(jSliderNoir.getValue()+1); 
    }//GEN-LAST:event_jSliderBlancMouseReleased

    private void jSliderBlancStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBlancStateChanged
        int sNoir = jSliderNoir.getValue();
        int sBlanc = jSliderBlanc.getValue();
        
        if (sBlanc > sNoir)
        {
            blanc = Min + (Max-Min)*(double)sBlanc/(double)D;
            jTextFieldBlanc.setText("" + blanc);
        }
        
        MiseAJourCImage();
    }//GEN-LAST:event_jSliderBlancStateChanged

    private void jSliderNoirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNoirStateChanged
        int sNoir = jSliderNoir.getValue();
        int sBlanc = jSliderBlanc.getValue();
        
        if (sBlanc > sNoir)
        {
            noir = Min + (Max-Min)*(double)sNoir/(double)D;
            jTextFieldNoir.setText("" + noir);
        }

        MiseAJourCImage();
    }//GEN-LAST:event_jSliderNoirStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoubleMatrix(new JFrame(), true,null,null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabelValeurMax;
    private JLabel jLabelValeurMin;
    private JScrollPane jScrollPane1;
    private JSlider jSliderBlanc;
    private JSlider jSliderNoir;
    private JTextField jTextFieldBlanc;
    private JTextField jTextFieldNoir;
    // End of variables declaration//GEN-END:variables
    
}
